export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"; 
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

export const FETCH_USER_OFFERS = "FETCH_USER_OFFERS";
export const FETCH_USER_OFFERS_START = "FETCH_USER_OFFERS_START";
export const FETCH_USER_OFFERS_SUCCESS = "FETCH_USER_OFFERS_SUCCESS"; 
export const FETCH_USER_OFFERS_FAIL = "FETCH_USER_OFFERS_FAIL";

export const POST_DATA = "POST_DATA";
export const POST_DATA_START = "POST_DATA_START";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS"; 
export const POST_DATA_FAIL = "POST_DATA_FAIL";
export const POST_DATA_CLEAR = "POST_DATA_CLEAR";

export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_START = "DELETE_DATA_START";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"; 
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const FILTER_DATA ="FILTER_DATA";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_STATE_CHANGE = "AUTH_STATE_CHANGE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
